---
title: "Analysis"
output: rmarkdown::html_vignette
date: "`r Sys.time()`"
vignette: >
  %\VignetteIndexEntry{Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#remotes::install_github("mrustl/tigo")
library(tigo)

datetime_min <- Sys.time() - 5*24*3600 #last five days (< 100 MB !!!)
tigo_data <- tigo::get_data_aggregate(datetime_min = datetime_min) 
str(tigo_data)

interactive <- TRUE
```


## P_in 

```{r plot_pin, fig.height=15, fig.fullwidth=TRUE}
tigo::plot_data(data = tigo_data, param = "Pin", interactive)
```

## V_in 

```{r plot_vin, fig.height=10, fig.fullwidth=TRUE}
tigo::plot_data(data = tigo_data, param = "Vin", interactive)
```

## I_in 

```{r plot_iin, fig.height=10, fig.fullwidth=TRUE}
tigo::plot_data(data = tigo_data, param = "Iin", interactive)
```

## RSSI 

```{r plot_rssi, fig.height=10, fig.fullwidth=TRUE}
tigo::plot_data(data = tigo_data, param = "RSSI", interactive)
```

## String 

### Voltage 

```{r plot_vin_sum}
plot_string_sum(tigo_data)
```

```{r plot_vin_n}
plot_string_sum(tigo_data, ypara = "n")
```
